# Netlify configuration for the ui-betslip standalone app

[build]
  # This command builds the standalone version of your component
  command = "npm run build:standalone"
  
  # Netlify will deploy the contents of this directory
  publish = "dist/standalone"

# You can set the Node.js version for the build environment
[build.environment]
  NODE_VERSION = "22"

# Reminder: 
# You must set your WebSocket URL in the Netlify UI.
# Go to Site settings > Build & deploy > Environment and add a variable:
# Key: VITE_WS_URL
# Value: wss://your-production-websocket-url.com
